apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend